spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: ms-eurekaserver
      password: teste

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
