spring:
  application:
    name: mscloudgateway
  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/mscredito
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://ms-eurekaserver:teste@localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'