spring:
  application:
    name: msavaliador
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 0
  servlet:
    contextPath: /v1/api/

mq:
  queues:
    emisao-cartao: emisao-cartao

eureka:
  client:
    serviceUrl:
      defaultZone: http://ms-eurekaserver:teste@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'
